### ISSUE TITLE
Export report to JSON

### ISSUE THREAD

**Issue by Kilo-411** [carlospolop/PEASS-ng#142]
hey @carlospolop, thanks for answering. (still @acmello just using the appropriated account for this lol), I actually started to experiment with the idea as a side thing but since its something interesting for everyone, I might as well fork the project and make an actual contribution :) but you are alright, its really time consuming. 

I was thinking in something along the lines of: 
https://gist.github.com/hatecomputers/b49639fd72caec7c208961be46411341

Let me know if you have any thoughts or better ideas for naming it. cc @necrose99

_Originally posted by @hatecomputers in https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/issues/43#issuecomment-843134782_

**Comment by Kilo-411** [comment]
`note`

**Comment by carlospolop** [comment]
Hi @Kilo-411,
It looks very good, but please, check out my comment on #43 about adding the colours used to the JSON.

**Comment by hatecomputers** [comment]
Can we just change the issue's title to something like "JSON output" or "Export report to JSON"? :)

**Comment by carlospolop** [comment]
Hi guys, basically I'm preparing big changes for PEASS and this is a very important part in those changes.
I would need a python script capable of reading a linpeas/winpeas output and creating a JSON this week.
Let me know if anyone wants to do that, or I will start working on it.

**Comment by hatecomputers** [comment]
hey @carlospolop. can't really do this week unfortunately. I imagine you probably has some ideas about how to approach the report to convert it into JSON but if you wanna discuss it at some point let me know. As I said, I'm swamped with work stuff but still would love to contribute somehow.

**Comment by carlospolop** [comment]
Hi mate, I will be doing several changes in linpeas and winpeas these months in order to try to present them in some nice international conferences. As I want to perform several changes, it would be awesome to have this JSON formatter for the end of this month.
I'm also changing a bit the output of linpeas and winpeas to make the creation of this formmater a bit easier.
If you could take care of this script for the end of the month it would be great for me as I could be able to focus on improving other parts of the PEAS.
So, please, let me know if you think you would be able to find the time to develop this script for the end of this month or not. And thanks for the interest! :)

**Comment by hatecomputers** [comment]
hey @carlospolop. I have a couple of days slow days in the horizon and wanna start working on export feature. Are the changes you mentioned previously are up as part of the latest commit? 

Regardless, reach out to me telegram (@hatecomput3rs) if you feel like speed things up :)

**Comment by carlospolop** [comment]
Thanks for your help with https://github.com/carlospolop/PEASS-ng/tree/master/parser mate!
